"""Generated views: EPOCH.md and the terminal status block.

Nothing here reads state from disk; it is handed model objects and returns text.

There is deliberately no STATUS.md renderer. The status view mixes the worklog with
leases and git ahead/behind — machine-local facts that change with no command running
— so a committed file could only ever be wrong about them. `clarity status` composes
it on every run instead, which is the one place all three inputs are live.
"""

from __future__ import annotations

import shutil
import sys
import textwrap
from datetime import datetime

from .model import CLOSED, FUTURE, IN_FLIGHT, Item, Objectives

# Wrapped here, not by the terminal, so zooming or resizing never re-flows the output.
# Capped rather than fixed: a terminal narrower than the cap would wrap it again itself,
# which is the ugliness we're avoiding. Piped output ignores the terminal entirely.
MAX_WIDTH = 120
# Derived from the head format below, never hardcoded: a mismatch lands continuation
# lines a column off from the name, which reads as a misprint.


def width() -> int:
    if not sys.stdout.isatty():
        return MAX_WIDTH  # stable for files and pipes
    return max(48, min(MAX_WIDTH, shutil.get_terminal_size((MAX_WIDTH, 24)).columns - 1))

MARK = "<!-- GENERATED by clarity — edit config.yaml or use clarity commands -->"
EPOCH_MARK_END = "<!-- /GENERATED — write your own notes below this line -->"

_LABEL = {
    "idea": "IDEA",
    "planned": "PLANNED",
    "active": "EPOCH",
    "blocked": "BLOCKED",
    "done": "DONE",
    "abandoned": "DROPPED",
}

# Single-width glyphs on purpose: emoji are double-width in most terminals and would
# push the id column out of true, differently per font.
_GLYPH = {
    "idea": "·",
    "planned": "○",
    "active": "▸",
    "blocked": "⏸",
    "done": "✓",
    "abandoned": "✗",
}


def _wrap(text: str, first: str, rest: str, cols: int) -> list[str]:
    return textwrap.wrap(text, width=cols, initial_indent=first, subsequent_indent=rest,
                         break_long_words=False, break_on_hyphens=False) or [first.rstrip()]



def note_age(item: Item) -> str | None:
    """How long the record has been standing still, for an epoch in flight.

    This exists because of a real failure: a session reversed the scope of its own
    epoch, tested it, had the result reviewed and rewrote it three times without
    writing one note, because every turn felt mid-task and a note was never the
    thing just asked for. Nothing in the view said so. Now it does — `status` is
    what an agent reads first, so it is where the nag belongs.
    """
    if item.status not in IN_FLIGHT or not item.notes:
        return None
    latest = max(n.at for n in item.notes)
    try:
        when = datetime.fromisoformat(latest)
    except ValueError:
        return None
    # A pre-timestamp note is a bare date, which parses as midnight — so its age
    # is coarse rather than absent. Better a day-granular nag on an old worklog
    # than silence on exactly the projects most likely to have gone quiet.
    minutes = int((datetime.now() - when).total_seconds() // 60)
    if minutes < 90:
        return None          # still warm; saying anything here is just noise
    if minutes < 60 * 24:
        return f"last note {minutes // 60}h ago"
    return f"last note {minutes // 1440}d ago"


def _line(item: Item, leases: dict | None = None, cols: int | None = None,
          stale: dict | None = None) -> str:
    """Name first, detail on its own indented line — never a separator left dangling."""
    cols = cols or width()
    label = _LABEL.get(item.status, item.status.upper())
    held = (leases or {}).get(item.id)
    head = f"  {_GLYPH.get(item.status, ' ')} {label:<8} {item.id:>3}  "
    gutter = " " * len(head)  # every wrapped line starts under the name

    lines = _wrap(item.name, head, gutter, cols)

    detail = ""
    if item.status == "blocked" and item.blocked_reason:
        detail = f"blocked: {item.blocked_reason}"
    elif item.status in CLOSED and item.outcome:
        detail = f"outcome: {item.outcome}"
    elif item.folder:
        detail = item.folder
    if held:
        # the age is the whole judgement: nothing expires, so you decide if it's stale
        who = f"{held.get('owner', '?')}@{held.get('host', '?')}"
        since = held.get("age")
        detail += f"   [held by {who}{', ' + since if since else ''}]"
    if detail:
        lines += _wrap(detail, gutter, gutter, cols)
    quiet = note_age(item)
    if quiet:
        # its own line for the same reason the refresh warning gets one: it is about
        # the record, not about where the work lives
        lines += _wrap(f"⚠ {quiet} — clarity note {item.id} \"...\"", gutter, gutter, cols)
    trails = (stale or {}).get(item.id)
    if trails:
        # its own line, not tacked onto the folder path: main moving under an epoch is
        # the thing you want to notice, and it must not wrap into the path above it
        lines += _wrap(f"⚠ {trails} — clarity epoch refresh {item.id}", gutter, gutter, cols)
    return "\n".join(lines)


def status_text(objectives: Objectives, items: list[Item], show_all: bool = False,
                leases: dict | None = None, is_repo: bool = True,
                stale: dict | None = None) -> str:
    """The one-screen view. Printed, never written down — see the module docstring."""
    cols = width()
    out = []
    for label, text in (("OBJECTIVE", objectives.overall), ("NOW", objectives.current)):
        out += _wrap(text or "— not set —", f"{label:<11}", " " * 11, cols)
    out.append("")
    # What's ahead is a queue, oldest first — the top of the list is what to pick up.
    # What's finished is a stack, newest on top — recent work is what you look back for.
    groups = [("In flight", IN_FLIGHT, False), ("Up next", FUTURE, False)]
    if show_all:
        # Closed is what you finished; dropped work gets its own group, so scanning
        # what shipped is never interleaved with what you gave up on.
        groups += [("Closed", {"done"}, True), ("Dropped", {"abandoned"}, True)]

    for title, statuses, newest_first in groups:
        chosen = [i for i in items if i.status in statuses]
        # closed_seq is exact where it exists; a project that predates it falls back to
        # the date, which is how these read before, so old worklogs keep their order.
        chosen.sort(key=lambda i: (i.closed_seq or 0, i.ended or i.created or "", i.id),
                    reverse=newest_first)
        out.append(f"{title} ({len(chosen)})")
        out.append("─" * min(cols, 72))
        if not chosen:
            out.append("  —")
        for index, item in enumerate(chosen):
            block = _line(item, leases, cols, stale)
            out.append(block)
            # only where two lines could read as two items — and never before the
            # blank line that already closes the group
            if "\n" in block and index < len(chosen) - 1:
                out.append("")
        out.append("")

    if not show_all:
        closed = len([i for i in items if i.status in CLOSED])
        out.append(f"{closed} closed or dropped — clarity status --all")
    if not is_repo:
        out.append("not a git repo — epochs have no branch or worktree")
    return "\n".join(out).rstrip() + "\n"


def epoch_md(item: Item, existing: str | None = None) -> str:
    """Generated block on top; anything the human wrote below is preserved.

    Deliberately does not index PLANS/. That directory is one anyone can drop a file
    into, so no command can know when it changed — caching the listing here is what
    forced every epoch to be re-rendered on every write. `clarity q item` lists it live.
    """
    lines = [
        MARK,
        f"# {item.id:03d} · {item.name}",
        "",
        f"- **type** {item.type}",
        f"- **status** {item.status}",
    ]
    if item.branch:
        lines.append(f"- **branch** {item.branch}")
    if item.repos:
        lines.append(f"- **repos** {', '.join(item.repos)}")
    if item.description:
        lines.append(f"- **goal** {item.description}")
    if item.blocked_reason:
        lines.append(f"- **blocked** {item.blocked_reason}")
    if item.outcome:
        lines.append(f"- **outcome** {item.outcome}")
    lines.append(f"- **started** {item.started or '—'}    **ended** {item.ended or '—'}")

    if item.notes:
        lines += ["", "## Tried"]
        lines += [f"- `{n.at.split()[0]}` {n.text}" for n in item.notes]
    lines += ["", EPOCH_MARK_END, ""]
    generated = "\n".join(lines)

    tail = ""
    if existing and EPOCH_MARK_END in existing:
        tail = existing.split(EPOCH_MARK_END, 1)[1].lstrip("\n")
    return generated + tail
